FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY . /app

# Install dependencies
RUN pip install  -r requirements.txt

# Expose port 5000 for Flask
EXPOSE 5000

# Set the command to run the application
CMD ["python", "visitor_count.py"]